### ISSUE TITLE
Requesting pre-processed datasets

### ISSUE THREAD

**Issue by KaIi-github** [histocartography/zoommil#11]
Hello Kevin,
      Thanks for your great work, I was learning the code you provided and found that data preprocessing is a difficult thing for me, can you provide the preprocessed files of CAMELYON16. It's important to me, thank you very much!!(^.^)

**Comment by KaIi-github** [comment]
①：
Traceback (most recent call last):
  File "/zoommil-main/bin/preprocess.py", line 311, in <module>
    patch_size=args.patch_size)
  File "/zoommil-main/bin/preprocess.py", line 50, in run
    seed=1)
  File "/zoommil-main/zoommils/utils/preprocessing.py", line 146, in __init__super().__init__(**kwargs)
  File "/anaconda3/envs/zoommils/lib/python3.7/site-packages/histocartography/preprocessing/feature_extraction.py", line 1028, in __init__super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'extraction_layer'

**First of all, the feature extractor made a keyword error, which temporarily solved the problem after removing it(extraction_layer)**

②：
Traceback (most recent call last):
  File "/zoommil-main/bin/preprocess.py", line 311, in <module>
    patch_size=args.patch_size)
  File "/zoommil-main/bin/preprocess.py", line 70, in run
    valid_features = extract_features(image, extractor, mask_generator, magnifications, patch_size)
  File "/zoommil-main/bin/preprocess.py", line 123, in extract_features
    _, features = extractor.process(high_mag_img, mask)
  File "/anaconda3/envs/zoommils/lib/python3.7/site-packages/histocartography/pipeline.py", line 138, in process
    return self._process(*args, **kwargs)
  File "/zoommil-main/zoommils/utils/preprocessing.py", line 162, in _process
    return self._extract_features(input_image, mask)
  File "/zoommil-main/zoommils/utils/preprocessing.py", line 209, in _extract_features
    features = features.reshape(features.shape[0], 1024, 16, 16)
RuntimeError: shape '[128, 1024, 16, 16]' is invalid for input of size 262144

**After ①, the problem I encountered was as above(②), no matter how I adjusted the parameters, the obtained feature shape could only meet the 262214 size, which prevented me from obtaining the feature with dimension 1024**

**Comment by kevthan** [comment]
Hi, sorry for the late response. Unfortunately, we cannot share the pre-processed datasets since we do not own the datasets and cannot re-distribute derived versions of it. Your error seems to be caused by an older version of the histocartography library. 

This should be resolved by cloning the latest version as described [here](https://github.com/histocartography/zoommil?tab=readme-ov-file#histocartography).
